#!/bin/bash
set -euax

EXPNAM=$1 CDATE=$2 COMROT=${3:-$STMP/$USER} ARCDIR=${4:-$COMROT/archive} TMPDIR=${5:-$STMP/$USER/tmpdir}

echo -------------------------------------------------------------------------------------------------------------------
echo Starting the runfits for:
echo -------------------------------------------------------------------------------------------------------------------
echo "EXPNAM    " $EXPNAM       # argument 1 - experiment name    - required  (can be prod in which case COMROT is moot)
echo "CDATE     " $CDATE        # argument 2 - date of validation - required 
echo "COMROT    " $COMROT       # argument 3 - COMROT directory   - optional - defaults to /stmp/$USER
echo "ARCDIR    " $ARCDIR       # argument 4 - ARCDIR directory   - optional - defaults to $COMROT/archive 
echo "TMPDIR    " $TMPDIR       # argument 5 - TMPDIR directory   - optional - defaults to /stmp/$USER/tmpdir
echo -------------------------------------------------------------------------------------------------------------------

fitdir=${fitdir:-$(dirname $0)}; fitdir=$(cd $fitdir; pwd)
COMDAY=${COMDAY:-$COMROT/logs/$CDATE}

set -euax          

export OMP_NUM_THREADS=${FITOMP:-1}
export MPIRUN='mpirun'
export KMP_STACKSIZE=100M
export MPI_BUFS_PER_PROC=256
export MPI_BUFS_PER_HOST=256
export MPI_GROUP_MAX=256
ulimit -s 20000000; ulimit -a

export CDATE=$CDATE
export EXP=$EXPNAM
export COM_IN=$ROTDIR
export COM_INA=$ROTDIR
export COM_INF=$ROTDIR/vrfyarch

export fitdir=$fitdir
export ARCDIR=$ARCDIR
export TMPDIR=$TMPDIR
export ACPROFit=${ACPROFit:-YES}
export NEMS=${NEMS:-YES}   
export PRVT=${PRVT:-$BASE_GSM/fix/prepobs_errtable.global}
export HYBLEVS=${HYBLEVS:-$BASE_GSM/fix/fix_am/global_hyblev.l65.txt}

time $fitdir/runfits $EXPNAM $CDATE $COMROT

