#!/bin/bash
set -euax

EXPNAM=$1 CDATE=$2 ARCDIR=${ARCDIR:-$3} TMPDIR=${TMPDIR:-$4}


set +x
echo -------------------------------------------------------------------------------------------------------------------
echo Starting runfits: the following variables must be defined:
echo -------------------------------------------------------------------------------------------------------------------
echo "EXPNAM    " $EXPNAM       # argument 1 - experiment name    - required
echo "CDATE     " $CDATE        # argument 2 - date of validation - required
echo "ARCDIR    " $ARCDIR       # argument 4 - ARCDIR directory   - optional - defaults to $COMROT/archive
echo "TMPDIR    " $TMPDIR       # argument 5 - TMPDIR directory   - optional - defaults to /ptmp/$USER/tmpdir
echo "ACCOUNT   " $ACCOUNT      # inherited  - project code       - required - defaults to nothing
echo "COM_INA   " $COM_INA      # inheirited - project code       - required - defaults to nothing
echo "COM_INF   " $COM_INF      # inheirited - project code       - required - defaults to nothing
echo "OUTPUT_FILETYPE " $OUTPUT_FILETYPE    # inheirited - project code       - required - either nemsio or netcdf defaults to sigio
echo -------------------------------------------------------------------------------------------------------------------

fitdir=${fitdir:-$(dirname $0)}; fitdir=$(cd $fitdir; pwd)
COMDAY=${COMDAY:-$COMROT/logs/$CDATE}

set -euax

vrfytmpdiris=$TMPDIR
unset TMPDIR

cat<<eof | sbatch
#!/bin/bash --login
#SBATCH --job-name=FITS.$EXPNAM.$CDATE --time=00:20:00
#SBATCH --nodes=3 --ntasks-per-node=1
#SBATCH --output=$COMDAY/jet.fit2obs.log.$$
#SBATCH --account=$ACCOUNT
#SBATCH --qos=${CUE2RUN:-batch}
#SBATCH --partition=$PARTITION_BATCH



set -euax

set +x
 module purge
 module use /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack
 module load hpc/1.1.0
 module load hpc-intel/18.0.5.274
 module load hpc-impi/2018.4.274
 module load hdf5/1.10.6
 module load netcdf/4.7.4
 module list
set -x

export OMP_NUM_THREADS=${FITOMP:-1}
export MPIRUN="srun --export=ALL -n 3"
export KMP_AFFINITY=disabled

export CDATE=$CDATE
export EXP=$EXPNAM
export COMPONENT=${COMPONENT:-atmos}
export COM_IN=$ROTDIR
export KEEPDATA=$KEEPDATA

export fitdir=$fitdir
export ARCDIR=$ARCDIR
export TMPDIR=$vrfytmpdiris
export ACPROFit=${ACPROFit:-YES}
export NEMS=${NEMS:-YES}

time $fitdir/runfits $EXPNAM $CDATE

eof
